---
# 系统总览：智能告警平台
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: smart-alert-system
  description: "基于云原生平台智能告警平台"
spec:
  owner: user:guest

---
# 1. 业务应用 (图中 ID 3)
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: demo-app
  title: "Demo Application"
spec:
  type: service
  lifecycle: experimental
  owner: user:guest
  system: smart-alert-system

---
# 2. 监控核心 (图中 ID 4)
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: prometheus
  title: "Prometheus"
spec:
  type: service
  lifecycle: active
  owner: user:guest
  system: smart-alert-system
  dependsOn:
    - component:demo-app # 对应 Scrape Metrics 线条

---
# 3. 可视化 (图中 ID 5)
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: grafana
  title: "Grafana Dashboard"
spec:
  type: service
  lifecycle: active
  owner: user:guest
  system: smart-alert-system
  dependsOn:
    - component:prometheus # 对应 Visualize 线条

---
# 4. 告警管理 (图中 ID 6)
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: alert-manager
  title: "Alert Manager"
spec:
  type: service
  lifecycle: active
  owner: user:guest
  system: smart-alert-system
  dependsOn:
    - component:prometheus # 对应 Trigger Alert 线条

---
# 5. AI 引擎核心 (图中 ID 7)
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: robusta-ai
  title: "Robusta (AI Engine)"
spec:
  type: service
  lifecycle: active
  owner: user:guest
  system: smart-alert-system
  dependsOn:
    - component:alert-manager # 对应 Enrichment & RCA 线条

---
# 6. 通知通道 (图中 ID 8)
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: slack-alert-channel
  title: "Slack (Alert Channel)"
spec:
  type: communication
  owner: user:guest
  system: smart-alert-system
  dependencyOf:
    - component:robusta-ai # 对应 AI Recommendations

---
# 7. ITSM 工单系统 (图中 ID 9)
apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: servicenow-itsm
  title: "ServiceNow (ITSM)"
spec:
  type: itsm-tool
  owner: user:guest
  system: smart-alert-system
  dependencyOf:
    - component:robusta-ai # 对应 Auto Ticket
